# Generated by Django 5.2.7 on 2025-10-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='picked',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время сборки'),
        ),
    ]
